### ISSUE TITLE
Installation issue w.r.t nologin

### ISSUE THREAD

**Issue by kloetzl** [Antergos/antergos-repo-priority#2]
Running `pacman -Syu` I was greeted with the following error including a error from `nologin`.

![antergos-repo-priority-bug](https://cloud.githubusercontent.com/assets/7765807/15990791/1a0abb54-309f-11e6-99ce-be3db8e13004.png)

**Comment by lots0logs** [comment]
The script uses sudo to display a desktop notification (as it cannot be done under root). It looks like your sudo configuration blocked the script from running the command that would have displayed the desktop notification. There is no cause for concern. Let me know if you have any questions.
