### ISSUE TITLE
Missing rationale

### ISSUE THREAD

**Issue by kloetzl** [Antergos/antergos-repo-priority#3]
The documentation for this package states that it “adjusts the priority of the antergos repo in pacman.conf _as needed_.” I am wondering, why is that change needed, and why should I trust your repos more than arch core? With that rationale missing I fear this is a security issue.

**Comment by lots0logs** [comment]
I forgot to update the wiki article to include a link to the announcement post. Sorry about that! Here is the link: https://antergos.com/blog/antergos-repo-now-includes-latest-mate-cinnamon-packages/

**Comment by kloetzl** [comment]
Is Mate and Cinnamon the only reason? As a Gnome user I'll pass and stick to the old order.

**Comment by lots0logs** [comment]
Whatever works best for you :+1:
