### ISSUE TITLE
PKGBUILD - 1.0.4 zip file fails validity check

### ISSUE THREAD

**Issue by philwyettreb** [Antergos/antergos-repo-priority#5]
PKGBUILD - 1.0.4 zip file fails validity check.

md5sum in PKGBUILD is:

9dcbcf2588758aff4adeb6f3a5bad828

md5sum I get is:

20c4b916a78fab9874ad57e252b4a100

We really should not be using md5sum any longer and swap to sha256sum.

**Comment by lots0logs** [comment]
There are some PKGBUILDS that don't have matching checksum. This is because the build server updates the checksums before building the packages but does not update the pkgbuilds accordingly. Its been on the TODO list for quite some time, I'll get to it some day :grimacing:
